# Generated by Django 4.2.5 on 2023-09-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_avaiable',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_image',
            field=models.ImageField(upload_to='Variants'),
        ),
    ]
