# Generated by Django 4.2.5 on 2023-09-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_is_avaiable_products_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
