# Generated by Django 4.2.5 on 2023-09-20 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_offer_perc_products_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Is_offer_active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='offer_perc',
        ),
        migrations.RemoveField(
            model_name='products',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_offer',
        ),
        migrations.AddField(
            model_name='variant',
            name='Is_offer_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='offer_perc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='product_offer',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
