# Generated by Django 4.2.5 on 2023-09-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_products_is_offer_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='discount_price',
        ),
    ]
