# Generated by Django 6.0.2 on 2026-03-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_offer_price_variant_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
