# Generated by Django 4.2.5 on 2023-09-14 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('products', '0005_alter_variant_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='ordered', max_length=20)),
                ('payment_method', models.CharField(choices=[('PAYPAL', 'PayPal'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('RAZORPAY', 'RazorPay'), ('WALLET', 'Wallet')], max_length=20)),
                ('message', models.TextField(null=True)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('ORDERED', 'Ordered'), ('RETURNED', 'Returned'), ('SHIPPED', 'Shipped'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], default='ordered', max_length=20, null=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=150, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=150, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.useraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userorder.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variant')),
            ],
        ),
    ]
