# Generated by Django 4.2.5 on 2023-09-20 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='Is_offer_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_offer',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
