# Generated by Django 4.2.5 on 2023-09-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_variant_quantity_products_is_offer_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_perc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
